query food($offset: Int, $limit: Int) {
  food(offset: $offset, limit: $limit, order_by: {category: desc}) {
    id
    category
    title
    duration
    food_user {
      name
    }
    food_ratings_aggregate {
      aggregate {
        avg {
          rating
        }
      }
    }
    food_images {
      url
    }
  }
  food_aggregate {
    aggregate {
      count
    }
  }
}
