query food($offset: Int, $limit: Int,$id:uuid!) {
  food(offset: $offset, limit: $limit where: {user_id: {_eq: $id}}) {
    id
    category
    title
    duration
    user {
      name
    }
    ratings_aggregate {
      aggregate {
        avg {
          rating
        }
      }
    }
      images {
      url
    }
  }

}