query detail($id: uuid) {
  food(where: {id: {_eq: $id}}) {
    title
    duration
    description
    category
    user {
      name
    }
    images {
      url
    }
    steps(order_by: {stepNumber: asc}) {
      id
      instruction
      stepNumber
    }
    ratings_aggregate {
      aggregate {
        count(columns: created_at)
        avg {
          rating
        }
      }
    }
    Ingredients {
      Ingredient_id
      amount
      ingredient_name
      unit
    }
    Ingredients_aggregate {
      aggregate {
        count(columns: Ingredient_id)
      }
    }
    comments_aggregate {
      aggregate {
        count(columns: comment)
      }
    }
  }

}
