query detail($id: uuid) {
  food(where: {id: {_eq: $id}}) {
    title
    duration
    description
    category
    food_user {
      name
    }
    food_images {
      url
    }
    food_steps(order_by: {stepNumber: asc}) {
      id
      instruction
      stepNumber
    }
    food_ratings_aggregate {
      aggregate {
        count(columns: created_at)
        avg {
          rating
        }
      }
    }
    food_Ingredients {
      Ingredient_id
      amount
      ingredient_name
      unit
    }
    food_Ingredients_aggregate {
      aggregate {
        count(columns: Ingredient_id)
      }
    }
    food_comments_aggregate {
      aggregate {
        count(columns: comment)
      }
    }
  }

}
