query food($offset: Int, $limit: Int, $searchTerm: String!) {
  food(offset: $offset, limit: $limit, where:{title:{_ilike:$searchTerm}}){
    id
    category
    title
    duration
    user {
      name
    }
    rating_aggregate {
      aggregate {
        avg {
          rating
        }
      }
    }
     images {
      url
    }
  }
  food_aggregate {
    aggregate {
      count
    }
  }
}

