// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddRecipe: typeof import('./src/components/AddRecipe.vue')['default']
    Card: typeof import('./src/components/card.vue')['default']
    EthiopianDatePicker: typeof import('./src/components/inputs/ethiopian-date-picker.vue')['default']
    FingerprintInput: typeof import('./src/components/inputs/fingerprint-input.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HButton: typeof import('./src/components/inputs/h-button.vue')['default']
    HCheckbox: typeof import('./src/components/inputs/h-checkbox.vue')['default']
    HDatePicker: typeof import('./src/components/inputs/h-date-picker.vue')['default']
    HDragAndDrop: typeof import('./src/components/inputs/h-drag-and-drop.vue')['default']
    HEditor: typeof import('./src/components/inputs/h-editor.vue')['default']
    HFileUpload: typeof import('./src/components/inputs/h-file-upload.vue')['default']
    HListNew: typeof import('./src/components/inputs/h-list-new.vue')['default']
    HListNext: typeof import('./src/components/inputs/h-list-next.vue')['default']
    HMultipleSelect: typeof import('./src/components/inputs/h-multiple-select.vue')['default']
    HMultipleSelectNew: typeof import('./src/components/inputs/h-multiple-select-new.vue')['default']
    HMultipleSelectNext: typeof import('./src/components/inputs/h-multiple-select-next.vue')['default']
    HRadio: typeof import('./src/components/inputs/h-radio.vue')['default']
    HSelect: typeof import('./src/components/inputs/h-select.vue')['default']
    HTextArea: typeof import('./src/components/inputs/h-text-area.vue')['default']
    HTextField: typeof import('./src/components/inputs/h-text-field.vue')['default']
    InjectComp: typeof import('./src/components/injectComp.vue')['default']
    MyAccount: typeof import('./src/components/MyAccount.vue')['default']
    MyRecipes: typeof import('./src/components/MyRecipes.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Notification: typeof import('./src/components/notification.vue')['default']
    ProfilePictureInput: typeof import('./src/components/inputs/profile-picture-input.vue')['default']
    ProvideComp: typeof import('./src/components/ProvideComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/components/sign-up.vue')['default']
    SwitchToggle: typeof import('./src/components/inputs/switch-toggle.vue')['default']
  }
}
